services:
  # Database Server
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    networks:
      - backend

  # phpMyAdmin Container
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_gui
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - backend

  # Web Server (PHP + Apache)
  web:
    build: ./web-app
    # container_name: web_server
    restart: always
    depends_on:
      - db
    deploy:
      replicas: 2
    networks:
      - backend
  
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - backend

networks:
  backend:
    driver: bridge
